### ISSUE TITLE
filedate parsing when date field before the extension

### ISSUE THREAD

**Issue by eboustou** [RphWbr/visiannot#18]
exemple:
aaaaa_2020-10-10T11-11-11.ext
the function getDatetimeFromPath tries to parse 2020-10-10T11-11-11.ext

**Comment by RphWbr** [comment]
I cannot reproduce the bug. On "develop" branch, the function behaves correctly.

```
from visiannot.tools.datetime_converter import get_datetime_from_path

a = "aaaaa_2020-10-10T11-11-11.ext"
b = get_datetime_from_path(a, '_', 1, '%Y-%m-%dT%H-%M-%S')
print(b)
```
